### ISSUE TITLE
rss-datasource not able to load two different feeds

### ISSUE THREAD

**Issue by Jocomol** [VolkovLabs/volkovlabs-rss-datasource#10]
When using the link found on [this page](https://www.golem.de/sonstiges/rss.html) it loaded what it thought to be the feed but only showed the feed generator as a feed item (I think it's best if you try that out yourself to see what I mean)

When using the [other link](https://threatpost.com/feed) it just threw me a NetworkError.

**Comment by Jocomol** [comment]
I was able to resolve the first issue on my own by selecting "items" and not "channel" when creating the table, the second error remains though.

**Comment by mikhailredis** [comment]
@Jocomol, thank you for opening the issue.

I got `Origin https://demo.volkovlabs.io is not allowed by Access-Control-Allow-Origin.` from my demo server when accessing `https://www.golem.de/sonstiges/rss.html`. Probably it works only for your region.

When I am trying to connect to https://threatpost.com/feed I got `Request header field x-grafana-nocache is not allowed by Access-Control-Allow-Headers.`, which is Grafana's internal header and I am not sure how to disable it yet. Do you see the same error?

**Comment by bygmakavi** [comment]
Could you please try this one, it's the google G Suite status feed.
[](https://www.google.com/appsstatus/dashboard/da/feed.atom)

**Comment by mikhailredis** [comment]
@bygmakavi I don't see the link? Is it Google Workspace? https://www.google.com/appsstatus/dashboard/en/feed.atom

**Comment by bygmakavi** [comment]
yes it is :)

**Comment by mikhailredis** [comment]
@bygmakavi You should be able to see Google Workspace Atom feed using the latest version: https://github.com/VolkovLabs/volkovlabs-rss-datasource/releases/tag/v1.3.1

Please let me know if there is anything else.

**Comment by bygmakavi** [comment]
Thank you kind sir

**Comment by Jocomol** [comment]
I was able to get it to work with the vanilla RSS Feed by enabling the CORS-Proxy. Maybe the issue here is the same.

**Comment by bygmakavi** [comment]
> I was able to get it to work with the vanilla RSS Feed by enabling the CORS-Proxy. Maybe the issue here is the same.

Vanilla plugin dosent support ATOM feeds :(

**Comment by mikhailredis** [comment]
@Jocomol CORS-Proxy was not stable for me. It's great that it's working for you.
