### ISSUE TITLE
Error. Can't connect to RSS 1.0

### ISSUE THREAD

**Issue by MeikelLP** [VolkovLabs/volkovlabs-rss-datasource#18]
* Feed: `https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml`
* Grafana OSS v8.4.5 (4cafe613e)
* No logs

![image](https://user-images.githubusercontent.com/11669846/164170940-6b5f2845-8467-489e-809a-4fbc0e53e154.png)

**Comment by mikhail-vl** [comment]
@MeikelLP Thank you for submitting the issue. I will take a look and get back to you shortly.

**Comment by mikhail-vl** [comment]
@MeikelLP I am sorry for the delay. I added RSS 1.0 support and will release new version tomorrow.

![Screen Shot 2022-04-24 at 10 40 33 PM](https://user-images.githubusercontent.com/47795110/165012181-1d3f467d-fb96-41df-8c75-6d4f0dafba3c.png)

Please let me know if there is anything else.

**Comment by matzeeg3** [comment]
Hi, i get the same issue and if i browes to the url i see the first line like that:
<?xml version="1.0" encoding="UTF-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
whould this be fixed too?

**Comment by mikhail-vl** [comment]
@matzeeg3 Could you please send me the link to verify.

**Comment by matzeeg3** [comment]
its hosted insite of a docker system i can open it for access but not pubic. how can i send it to you

**Comment by mikhail-vl** [comment]
@MeikelLP @matzeeg3 New version 1.5.0 released with support for RSS 1.0: https://github.com/VolkovLabs/volkovlabs-rss-datasource/releases/tag/v1.5.0

Please test and let me know if it works for you.
I will submit to Grafana repository review today.

**Comment by MeikelLP** [comment]
@mikhail-vl Sadly I'm not an administrator at out company and I can't easily install a plugin from file. Would you mind updating the Plugin in the Grafana Store as well? https://grafana.com/grafana/plugins/volkovlabs-rss-datasource/

**Comment by matzeeg3** [comment]
@mikhail-vl i just updated the datasource, still not working.

**Comment by mikhail-vl** [comment]
@MeikelLP Data Source was reviewed and updated in the Grafana Store: https://grafana.com/grafana/plugins/volkovlabs-rss-datasource/. Please let me know if it works for you.

**Comment by matzeeg3** [comment]
@mikhail-vl  send the email. thanks a lot

**Comment by MeikelLP** [comment]
@mikhail-vl It works fine :)
