### ISSUE TITLE
Can't parse GitHub releases feed

### ISSUE THREAD

**Issue by vfauth** [VolkovLabs/volkovlabs-rss-datasource#21]
Hi,

It seems that a missing name property in GitHub Atom releases feed causes it to fail:
![image](https://user-images.githubusercontent.com/32266846/168113801-d08fc5dc-da43-4ff0-b675-98dda922c455.png)

The example feed (I tried some others): https://github.com/sonatype/nexus-public/releases.atom

I use the latest plugin version with Grafana 8.5.2. Other feeds work.

**Comment by mikhail-vl** [comment]
@vfauth Thank you for opening the issue. I will take a look shortly.

**Comment by mikhail-vl** [comment]
@vfauth I have fixed the missing author name and added parsing for `Author` and `Media:thumbnail` fields. I will release an updated version in an hour or so to test.

![Screen Shot 2022-05-12 at 12 59 58](https://user-images.githubusercontent.com/47795110/168129345-67e172e5-2ba9-49fa-b319-44107a6e714e.png)

Here is the code for Dynamic Text plugin to get you started:
```
<h2><a target="_blank" style="color: blue" href="{{link}}">{{title}}</a></h2>
<img src="{{media:thumbnail}}">
<b>{{date updated 'MMM, DD YYYY'}} by {{author}}</b>
<div>{{{content}}}</div>
<br/>
```

Please let me know if there is anything else.

**Comment by mikhail-vl** [comment]
@vfauth Could you please test and let me know if it works for you: https://github.com/VolkovLabs/volkovlabs-rss-datasource/releases/tag/v1.6.0

**Comment by vfauth** [comment]
It works perfectly, thank you very much!!

However the change to extract the author name automatically, while an unquestionable improvement, will probably break some dashboards which used author.name, so maybe you could list it in the changelog/release announcement.

**Comment by mikhail-vl** [comment]
@vfauth Thank you. I  will update the changelog to make it clear.
But I don't think that using `author.name` is possible. Because Data Source returns `[Object] string as a field` and does not support JSON objects. Or was it possible?

**Comment by vfauth** [comment]
It return an Object, but I was able to extract the author name with author.name, so I think the XML is parsed anyway.

At least, I was able to do it on the GitLab Blog RSS: https://about.gitlab.com/atom.xml

**Comment by mikhail-vl** [comment]
@vfauth Thank you for the feedback. Changelog updated and we released a new version: https://github.com/VolkovLabs/volkovlabs-rss-datasource/releases/tag/v1.6.2

Please let me know if there is anything else.
