### ISSUE TITLE
Trying to merge 3 RSS feeds into 1 text box

### ISSUE THREAD

**Issue by rhysmcqueen** [VolkovLabs/volkovlabs-rss-datasource#33]
Hi I am trying to find a way to add 3 rss data sources to aggregate into 1 text box. My goal is to display RSS feeds from AWS, Azure, GCP status pages to be displayed in 1 text box on Grafana. Could you provide any insight or recommendations.

**Comment by mikhail-vl** [comment]
@rhysmcqueen It should be possible to do by:
1) Create 3 RSS Data Sources.
2) Add data sources to the Dynamic Text panel by Marcus Olsson (marcusolsson-dynamictext-panel).
3) Using Transformation to merge them together.

Please let me know if you have any questions.

**Comment by mikhail-vl** [comment]
@rhysmcqueen Please let me know if you were able to do it or have any questions.

**Comment by mikhail-vl** [comment]
@rhysmcqueen Let us know if you need anything else.
