### ISSUE TITLE
monitor rss updates

### ISSUE THREAD

**Issue by tomdavidson** [VolkovLabs/volkovlabs-rss-datasource#34]
Can this plugin be used to monitor the frequency of updates on an RSS feed and be used as a source for alerts when expected updates are not available? I have approximately 100 feeds to monitor that should be updating several times a week.

**Comment by mikhail-vl** [comment]
@tomdavidson It's an interesting question. This plugin was designed to display an RSS feed, monitoring is a different use case.

  I am thinking of collecting feed updates as time series. Then adding monitoring and alerting using a time series panel.
  Let me know if there is anything else.

**Comment by tomdavidson** [comment]
Thanks for the quick response and clarity. It does seem to a different concern and prob worth a different plugin.
