### ISSUE TITLE
Can't use the data source to create a managed alert

### ISSUE THREAD

**Issue by klochowicz** [VolkovLabs/volkovlabs-rss-datasource#38]
when trying to create a managed alert, I get "Plugin is not available" when Grafana tries to execute the query.

The data source works fine when using the "Explore" feature.

(tried to raise this originally with Grafana support, but they pointed me here instead as they do not support 3rd party plugins)

**Comment by mikhail-vl** [comment]
@klochowicz The RSS/Atom Data source is not a backend data source and can't be used for Alerting.

  For alerting based on RSS/Atom feeds, you may try the Infinity Data Source: https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/

**Comment by klochowicz** [comment]
> @klochowicz The RSS/Atom Data source is not a backend data source and can't be used for Alerting.
> 
> For alerting based on RSS/Atom feeds, you may try the Infinity Data Source: https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/
> 
> Let us know if there is anything else.

thank you for the reply, is it most helpful. I will try Infinity Data Source.

**Comment by mikhail-vl** [comment]
@klochowicz Please let me know if it works for you.
