### ISSUE TITLE
How to grab image from RSS feed

### ISSUE THREAD

**Issue by gpinkos** [VolkovLabs/volkovlabs-rss-datasource#43]
The Youtube tutorial on the RSS plugin was easy to follow, but I can still not get the images from [this RSS feed ](https://www.industrialheating.com/rss/topic/2671-news)to appear.  Hoping to fix this by modifying the code below.

Thanks in advance for any help!

What I used in the code:
```
<table width=100% style='border:0'>
  <tr><td style='border:0'><h3>
    <a targeet="_blank" style="color:white"
    href="{{link}}">{{title}}</a></h3>
    {{{content:h4}}}</td>
    <td rowspan=2 style='border:0' width=50px>
      <div style='max-width: 100%; display: inline;
      height:auto '><img width=150px
      src="{{content:img-src}}"></div></td></tr><tr>
        <td style='border:0'><b>
          {{date pubDate 'MMM DD YYYY'}}
          </b></td></table>
```
Table view:
![image](https://user-images.githubusercontent.com/97072938/205489026-6d323512-8360-444d-b885-d58055d5ecc3.png)

What I see:
![image](https://user-images.githubusercontent.com/97072938/205488737-ef91beca-0297-46d1-8ef7-4c94980a79a1.png)

The images from the RSS feed appear to be in this style of formatting:
`<enclosure url="https://www.industrialheating.com/ext/resources/2022-website-images/120222-WisOven-web.png?1669987754" type="image/png" length="430845"/>`

**Comment by mikhail-vl** [comment]
@gpinkos, it's not really straightforward. You can use `#with` to get inside the `enclosure` element and then use the `@_url` element, which is a URL property inside `<img src="">`.

```
{{#with enclosure}}
  {{'@_url'}}
{{/with}}
```

  I will update README and create a custom helper in the DynamicText Panel to dump objects and help to see the parsed structure.

  The other issue is the `pubDate`. It's not in the native ISO or RFC formats, which can be parsed automatically. It should be converted to the proper date format using Transformations.

  Please let us know if there is anything else.

**Comment by gpinkos** [comment]
Thank you Mikhail.  Works beautifully now.

![imgcorrect](https://user-images.githubusercontent.com/97072938/205778060-17ee6bed-da14-48cb-b41b-412ee242f6e3.JPG)

**Comment by mikhail-vl** [comment]
@gpinkos Thank you for confirming.

**Comment by mikhail-vl** [comment]
@gpinkos Handlebars helper `{{json object}}` added to the Dynamic Text panel to dump the object's content: https://github.com/VolkovLabs/volkovlabs-dynamictext-panel/pull/121

  It will be available in the upcoming version.

![Screen Shot 2022-12-05 at 23 00 30](https://user-images.githubusercontent.com/47795110/205817360-1ffe58c5-d578-42f2-968e-4f41e1bee516.png)

  Let us know if there is anything else.
