### ISSUE TITLE
v3 digital signature issue?

### ISSUE THREAD

**Issue by owenhaynes** [VolkovLabs/volkovlabs-rss-datasource#57]
Looks like a issue with the signature in the newley released v3. Not sure if its a problem here or the grafana side
using grafana v10.0.2

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/1472893/939ce9a1-4651-4fa0-a596-512faf939bd3)

**Comment by mikhail-vl** [comment]
@owenhaynes Thank you for letting us know.

  I found an issue in the release script and will release a new version today.
  Strange that the validation script did not spot it.
  It will take a couple of days for the Grafana team to review and update the Grafana Catalog.

**Comment by mikhail-vl** [comment]
The new version has been submitted for review.

![Screenshot 2023-08-02 at 12 22 36](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/47795110/b863b697-e5f2-49a3-91b3-da15398d3d71)

**Comment by mikhail-vl** [comment]
@owenhaynes The data source was updated in the Grafana Catalog: https://grafana.com/grafana/plugins/volkovlabs-rss-datasource/

  Please verify and let us know if there is anything else.

**Comment by owenhaynes** [comment]
@mikhail-vl all is working thank you
