### ISSUE TITLE
Request blocked by CloudFlare firewall

### ISSUE THREAD

**Issue by imReker** [VolkovLabs/volkovlabs-rss-datasource#59]
Get HTTP 403 using this datasource. I tested it directly with curl and there was no problem
Feeds:
https://netblocks.org/feed

**Comment by mikhail-vl** [comment]
@imReker I can connect to `https://netblocks.org/feed` from our Grafana instance and see the feed.

  Please check your network connectivity and firewall rules from the Grafana instance.
