### ISSUE TITLE
Feed cannot be loaded

### ISSUE THREAD

**Issue by ralfbeckmann** [VolkovLabs/volkovlabs-rss-datasource#60]
The following FEDD cannot be loaded or displayed. Can someone tell me why?
https://wid.cert-bund.de/content/public/securityAdvisory/rss
In my opinion it is a RSS v2 feed...

**Comment by ralfbeckmann** [comment]
Any ideas?

**Comment by ralfbeckmann** [comment]
Any ideas?

**Comment by mikhail-vl** [comment]
@asimonok Could you please take a look. It's able to access the URL, but displays can't connect.
