### ISSUE TITLE
Can the cache time be lowered or caching of data be disabled completely?

### ISSUE THREAD

**Issue by ianpmurphy** [VolkovLabs/volkovlabs-rss-datasource#65]
I've tried using this module to display newsfeeds on screens within a company and we've found that what is displayed is close to useless as theres no way to get it to refresh. Sometimes panels will display an entry from a feed which has been removed days earlier. Obviously this makes it difficult to display anything coherent.

Is there any way to disable the caching (I'm pulling from an internal feed) or to lower the cache time to something more reasonable like 5 minutes?

**Comment by mikhail-vl** [comment]
@ianpmurphy I have a couple of questions for you to understand the issue:
  - Do you have Grafana OSS, Cloud or Enterprise?
  - Do you use internal newsfeed or something we can try externally?

  Data Source Caching is a Enterprise feature and we are looking into reproducing it using Grafana OSS.

**Comment by ianpmurphy** [comment]
This is an on prem grafana server pulling in an on prem-rss feed. The caching is not just slow, it doesn't work at all. Sometimes a feed entry will update a few hours later, but others will not update for months. Seriously, months. 

There doesn't seem to be any way to get the module to update what its displaying and I've tried everything.

**Comment by mikhail-vl** [comment]
@ianpmurphy It's the first time we hear about this issue. No-one reported this issue before.

  What is your Grafana version?
  Is it possible that it's cached in your browser? Can you try with different browser?
  We just released a new version 4.0.0. Could you please try it and let us know.

**Comment by ianpmurphy** [comment]
I just tried the following:
- I modified some rss content (its a simple .rss text file in a folder on iis)
- I verified that the web page was serving the updated rss file
- I updated to the latest grafana version 
- I updated the volkom plugin to version 4.0.0 of whats now known as business news
- I opened a dashboard with an instance of the volkov rss - it still displays the pre-edit values.

**Comment by mikhail-vl** [comment]
@ianpmurphy Thank you for the details.

@vitPinchuk Please try to reproduce the following steps.

**Comment by vitPinchuk** [comment]
Hi @ianpmurphy 
I made a simple rss in node.js with 2 routers.
The 1st returns a file that I can change, and the 2nd always returns a random number of items.
I have used both routes, all my changes are applied correctly after a page refresh. 
The panel does not cache the data.

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/2bf7c868-179f-4ab1-942e-23b5e01d6bcd)
![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/0c13eb60-4e54-478c-b817-b0643ee60c34)

Here a few examples 
my xml file 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
  <title>W3Schools Home Page</title>
  <link>https://www.w3schools.com</link>
  <description>Free web building tutorials</description>
  <item>
    <title>RSS Tutorial</title>
    <link>https://www.w3schools.com/xml/xml_rss.asp</link>
    <description>New RSS tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial 1</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial 2</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial 3</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
   <item>
    <title>XML Tutorial 4</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
</channel>

</rss>
```
view on dashboard 
![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/5ee885aa-42b7-4c52-8311-c6fa0bae123b)

I updated file 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
  <title>W3Schools Home Page</title>
  <link>https://www.w3schools.com</link>
  <description>Free web building tutorials</description>
  <item>
    <title>RSS Tutorial</title>
    <link>https://www.w3schools.com/xml/xml_rss.asp</link>
    <description>New RSS tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial 1</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
   <item>
    <title>XML Tutorial 4</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
</channel>

</rss>
```
I see corret data 
  

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/adb77251-de93-46f1-b7ec-ac8630c8fd3f)

There is code as example. You can try run it local and checked 
index.js file 
```javascript
const express = require("express");
const xmlbuilder = require("xmlbuilder");
const fs = require("fs");
const path = require("path");

const app = express();
const port = 8001;

app.get("/feed", (req, res) => {
  const xml = generateRandomXml();
  res.type("application/rss+xml");
  res.send(xml);
});

app.get("/rss", (req, res) => {
  const filePath = path.join(__dirname, "xml", "rss.xml");
  fs.readFile(filePath, "utf8", (err, data) => {
    if (err) {
      console.error(err);
      res.status(500).send("Internal Server Error");
    } else {
      res.type("application/xml");
      res.send(data);
    }
  });
});

function generateRandomXml() {
  const root = xmlbuilder.create("rss");
  root.att("version", "2.0");

  const channel = root.ele("channel");
  channel.ele("title", "Random RSS Feed");
  channel.ele("link", "https://example.com");

  for (let i = 0; i < Math.floor(Math.random() * 25 + 1); i++) {
    const item = channel.ele("item");
    item.ele("title", `Item ${i}`);
    item.ele("description", `This is item ${i}`);
  }

  return root.end({ pretty: true });
}

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```
package.json file 
```json
{
  "dependencies": {
    "express": "^4.19.2",
    "fs": "^0.0.1-security",
    "kill-port": "^2.0.1",
    "path": "^0.12.7",
    "xmlbuilder": "^15.1.1"
  },
  "scripts": {
    "start": "node index.js"
  }
}

```
the app structure
![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/5ad1db3d-82bb-4265-9566-418df94da186)

rss.xml file in xml folder 
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
  <title>W3Schools Home Page</title>
  <link>https://www.w3schools.com</link>
  <description>Free web building tutorials</description>
  <item>
    <title>RSS Tutorial</title>
    <link>https://www.w3schools.com/xml/xml_rss.asp</link>
    <description>New RSS tutorial on W3Schools</description>
  </item>
  <item>
    <title>XML Tutorial 1</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
   <item>
    <title>XML Tutorial 4</title>
    <link>https://www.w3schools.com/xml</link>
    <description>New XML tutorial on W3Schools</description>
  </item>
</channel>

</rss>
```

1.Make folder with app name
2. create package.json
3. create index.js file
4. make into App folder folder with name "xml"
5. place rss.xml file into "xml" folder
6. run in terminal `npm i`
7. app start witn `npm run start`
works in port 8001
