### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by malosaa** [VolkovLabs/volkovlabs-rss-datasource#66]
Hi,

i did try to install the plugin, however it fails.
Any idea why it does not work ?

Using 9.4.7 on proxmox.

regards

**Comment by mikhail-vl** [comment]
@malosaa Do you have any other community plugins installed on this Grafana instance?

  I have not used proxmox, can it be permission issues?
  Check the Grafana logs for more information what happened.

**Comment by mikhail-vl** [comment]
@malosaa You can see the logs in the container's output.

  Please review them and let us know if you see any installation issues. I just successfully installed the latest version 3.1.0 to the Grafana Cloud.
