### ISSUE TITLE
Zoom RSS failed to be retrieved

### ISSUE THREAD

**Issue by duj4** [VolkovLabs/volkovlabs-rss-datasource#67]
I am trying to retrieve the RSS info from https://status.zoom.us via this plugin, but the test did not pass with error below:
![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/19278537/e693b905-ce45-4963-8038-f163b24a87ab)

From the grafana.log I could find:
> logger=sqlstore.transactions t=2024-04-17T22:42:52.799459669+08:00 level=debug msg="skip committing the transaction because it belongs to a session created in the outer scope"
> logger=sqlstore.transactions t=2024-04-17T22:42:52.799484233+08:00 level=debug msg="skip committing the transaction because it belongs to a session created in the outer scope"

Seems this is related to https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/news/, thus I added nginx in front of the Grafana with config below:
```
server{
    listen 443 ssl; 
    server_name <server name A>; 
    ssl_certificate  <cert path>;  
    ssl_certificate_key <key path>;      
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;            
	location / { 
        if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
        }
        if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        }
        if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        }
        proxy_pass https://<server name B>:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header Referer https://<server name B>:3000;
	}
}
```
Issue kept still.

May I know if there is any thing mis-configured?

Grafana version: 10.2.2
Plugin version: 3.1.0

**Comment by mikhail-vl** [comment]
@duj4 `https://status.zoom.us` is not a RSS Feed, it's a web-page.

  The RSS feed URL is: https://status.zoom.us/history.rss.
  I tried it and it works as expected.

**Comment by duj4** [comment]
Thanks @mikhail-vl , may I know how you find out the correct URL? When I checked the history.rss, it does display the operational status, or this is not part of RSS?

**Comment by mikhail-vl** [comment]
@duj4 You can check the Atom feed, it may have required information. Maybe it's in the RSS feed, but not parse properly.

![Screenshot 2024-04-17 at 1 20 03 PM](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/47795110/e2b157b2-9905-46cb-bc5a-a607bed0fe99)

**Comment by duj4** [comment]
Thanks @mikhail-vl
