### ISSUE TITLE
Wordpress https://<blog>/feed URIs appear not to work

### ISSUE THREAD

**Issue by abctaylor** [VolkovLabs/volkovlabs-rss-datasource#70]
Hello - I've tried a few WordPress RSS feeds and always tend to get this error:

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/30197206/af307c88-2c8f-4ff6-9165-f05c7f38b25f)

For example:
- https://prodata.ie/feed
- https://blog.abctaylor.com/feed

Any ideas? These URLs curl fine on the server running Grafana.

**Comment by vitPinchuk** [comment]
Hi @abctaylor 
Adding `/` at the end may solve the problem. Instead `https://blog.abctaylor.com/feed` please use `https://blog.abctaylor.com/feed/`

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/0c4ecc43-8461-467b-aff0-5498caaa16a0)
  
  
without `/` at the end

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/146737590/0c8e98e7-f543-4a8a-97dc-8a5a17748e71)


But if you already have a data source with `https://blog.abctaylor.com/feed` and after adding `/` and running the test you will get an error
After adding `/` at the end, please clear cache and use hard reload

**Comment by mikhail-vl** [comment]
Documentation updated: https://volkovlabs.io/plugins/volkovlabs-rss-datasource/provisioning/

**Comment by mikhail-vl** [comment]
@abctaylor Thank you for confirming.

  We updated documentation and added toolbar to the Feed URL to make it clear.
