### ISSUE TITLE
tag in items getting scrambled

### ISSUE THREAD

**Issue by timlevett** [VolkovLabs/volkovlabs-rss-datasource#74]
I had a weird issue using this datasource. The RSS feed had a `<tag>` field in each record, and they were getting mixed up. So for example if item 1 had "test" as the tag, and item 2 had "prod" in as the tag, the table output in Grafana would show item 1 with tag for item 2.

Have you ever ran into this?

**Comment by mikhail-vl** [comment]
@timlevett I don't think I have heard about such issue before.

  Could you please send us the URL of the feed and/or example to try ourself.

**Comment by timlevett** [comment]
@mikhail-vl here is the one I experienced it with; https://grafana.com/docs/grafana-cloud/whats-new/index.xml.

Here is example where the first one is pulling the data using Infinity Datasource and the bottom one is the rss-datasource. 

![image](https://github.com/VolkovLabs/volkovlabs-rss-datasource/assets/3534544/7bc78514-dfe4-4894-a395-809dcaeceaf1)

As you can see, the K6 titles are not aligning to the tag in the RSS feed datasource driven, but it works fine in the Infinity datasource. I'm curious if the sort is messing it up, but its the same panel (Table), so it should behave the same across both.

Attached the sample json dashboard.

[example.dash.json](https://github.com/VolkovLabs/volkovlabs-rss-datasource/files/15383903/example.dash.json)

**Comment by mikhail-vl** [comment]
@timlevett Thank you for providing details.

  @vitPinchuk Please investigate.
